package org.agroplanner.shared.exceptions;

/**
 * Indicates a failure during the data export.
 *
 * <p><strong>Architecture & Design:</strong></p>
 * <ul>
 * <li><strong>Pattern:</strong> Implements the <em>Exception Translation</em> pattern.</li>
 * <li><strong>Abstraction Boundary:</strong> Service layer components catch low-level technical exceptions
 * (specifically {@link java.io.IOException}) generated by file operations and wrap them in this
 * domain-specific exception. This encapsulates the underlying storage mechanism details, preventing
 * implementation leakage into the Controller layer.</li>
 * </ul>
 *
 * @see TerrainExceptions
 */
public class ExportException extends TerrainExceptions {

    /**
     * Constructs a new exception with the specified detail message regarding the export failure.
     *
     * @param message The detail message explaining the context of the error.
     */
    public ExportException(String message) {
        super(message);
    }

    /**
     * Constructs a new exception with the specified detail message and the underlying cause.
     *
     * <p><strong>Exception Chaining:</strong></p>
     * Preserves the stack trace of the original technical error (the "cause") for debugging purposes,
     * while allowing the application to handle the error at a higher level of abstraction.
     *
     * @param message The detail message.
     * @param cause   The original low-level exception (e.g., {@link java.io.IOException}).
     */
    public ExportException(String message, Throwable cause) {
        super(message, cause);
    }
}
