package org.agroplanner.domainsystem.model;

import org.agroplanner.gasystem.model.Individual;

import java.awt.geom.Rectangle2D;

/**
 * Defines the abstract contract for geometric spatial constraints within the simulation.
 *
 * <p><strong>Architecture & Design:</strong></p>
 * <ul>
 * <li>Concrete implementations (e.g., {@code CircleDomain}, {@code RectangleDomain})
 * represent specific geometric strategies for defining valid cultivation areas.</li>
 * <li><strong>Role:</strong> Encapsulates the mathematical definition of the <strong>Feasible Region</strong>.
 * The Evolutionary Algorithm relies on this interface to determine the fitness validity of solutions
 * without knowledge of the underlying geometry (Polymorphism).</li>
 * </ul>
 */
public interface Domain {

    /**
     * Evaluates the fundamental geometric inequality for the specific shape.
     *
     * <p><strong>Performance Note:</strong></p>
     * This method represents the "Hot Path" of the geometric validation, called repeatedly during
     * the fitness evaluation phase. Implementations should rely on efficient mathematical primitives
     * (e.g., Euclidean distance checks) rather than complex object allocations.
     *
     * @param x The Cartesian X-coordinate to test.
     * @param y The Cartesian Y-coordinate to test.
     * @return {@code true} if the coordinate lies <strong>strictly outside</strong> the feasible boundaries;
     * {@code false} if it resides inside or on the boundary.
     */
    boolean isPointOutside(double x, double y);

    /**
     * Validates the spatial integrity of a complete candidate solution.
     *
     * <p><strong>Constraint Satisfaction:</strong></p>
     * Iterates over the phenotype of the {@link Individual}, verifying that every distinct plant
     * position respects the domain boundaries. A solution is considered valid if and only if
     * <strong>all</strong> constituent points satisfy the {@link #isPointOutside(double, double)} predicate.
     *
     * @param individual The candidate solution generated by the Genetic Algorithm.
     * @return {@code true} if the entire chromosome configuration is spatially valid, {@code false} otherwise.
     */
    boolean isValidIndividual(Individual individual);

    /**
     * Computes the Minimum Bounding Rectangle (MBR) enclosing the geometric shape.
     *
     * <p><strong>Algorithmic Usage (Rejection Sampling):</strong></p>
     * This rectangle defines the sampling limits for the initial population generation.
     * The system generates random coordinates within this box and then filters them using
     * {@link #isPointOutside(double, double)}. This optimizes generation efficiency by confining
     * randomness to a relevant subset of the 2D plane.
     *
     *
     * @return A {@link Rectangle2D} defining the outer limits (min/max X, min/max Y) of the domain.
     */
    Rectangle2D getBoundingBox();
}
